import assert from "node:assert/strict"
import { test } from "node:test"
import {
  estimateCharTokens,
  estimateContextWindowStats,
  estimateMcpSchemaTokens,
  estimateTurnPerformance
} from "./context-token-estimator.ts"

test("estimateContextWindowStats calculates tokens and percentage", () => {
  const stats = estimateContextWindowStats(
    [
      {
        id: "1",
        role: "user",
        content: "hello world",
        createdAt: Date.now()
      }
    ],
    "claude-3-7-sonnet"
  )

  assert.equal(stats.maxTokens, 200_000)
  assert.equal(stats.usedTokens, estimateCharTokens("hello world".length))
  assert.ok(stats.usedTokens > 0)
  assert.equal(stats.buckets.length, 5)
})

test("estimateContextWindowStats is zero without messages rules or tools", () => {
  const stats = estimateContextWindowStats([], "claude-3-7-sonnet")
  assert.equal(stats.usedTokens, 0)
  assert.equal(stats.usagePercent, 0)
})

test("estimateContextWindowStats ignores excluded chips", () => {
  const statsActive = estimateContextWindowStats([], "claude-3-7-sonnet", [], [], [], [
    { snippet: "a".repeat(380), enabled: true }
  ])

  const statsExcluded = estimateContextWindowStats([], "claude-3-7-sonnet", [], [], [], [
    { snippet: "a".repeat(380), enabled: false }
  ])

  assert.ok(statsActive.usedTokens > statsExcluded.usedTokens)
  const memActive = statsActive.buckets.find((bucket) => bucket.id === "memory")?.tokens ?? 0
  const memExcluded = statsExcluded.buckets.find((bucket) => bucket.id === "memory")?.tokens ?? 0
  assert.equal(memActive, 100)
  assert.equal(memExcluded, 0)
})

test("estimateMcpSchemaTokens uses name and description only", () => {
  const cost = estimateMcpSchemaTokens({
    id: "s1",
    name: "github",
    transport: "stdio",
    command: "npx",
    trusted: true,
    connected: true,
    allowedResourceUris: [],
    tools: [
      {
        name: "create_issue",
        description: "Create a GitHub issue"
      }
    ]
  })
  assert.equal(cost, estimateCharTokens("create_issue".length + "Create a GitHub issue".length))
})

test("estimateMcpSchemaTokens is zero without tools", () => {
  assert.equal(
    estimateMcpSchemaTokens({
      id: "s1",
      name: "empty",
      transport: "stdio",
      trusted: true,
      connected: true,
      allowedResourceUris: []
    }),
    0
  )
})

test("estimateTurnPerformance falls back to thoughtSeconds without inventing TTFO", () => {
  const perf = estimateTurnPerformance(
    null,
    [
      {
        id: "1",
        role: "assistant",
        content: "This is a test response generated by the model.",
        thoughtSeconds: 2,
        createdAt: Date.now()
      }
    ],
    false
  )

  assert.equal(perf.durationMs, 2000)
  assert.equal(perf.ttfoMs, 0)
  assert.ok(perf.tokensPerSecond > 0)
  assert.equal(perf.isLive, false)
})

test("estimateTurnPerformance respects TelemetryMetric when available", () => {
  const metric = {
    id: "m1",
    runId: "r1",
    kind: "agent",
    status: "ok",
    durationMs: 1500,
    ttfoMs: 280,
    outputTokens: 120,
    tokensPerSecond: 80.0,
    createdAt: Date.now()
  }

  const perf = estimateTurnPerformance(metric, [], true)
  assert.equal(perf.durationMs, 1500)
  assert.equal(perf.ttfoMs, 280)
  assert.equal(perf.outputTokens, 120)
  assert.equal(perf.tokensPerSecond, 80.0)
  assert.equal(perf.isLive, true)
})
