/**
 * 预设桶。electron 别名和 package exports 都指向这个文件。
 */
export {
  API_STYLES,
  API_STYLE_OPTIONS,
  adviseCatalogUrl,
  apiStyleLabel,
  catalogBaseCandidates,
  catalogPersistBase,
  CatalogError,
  defaultBaseURLFor,
  endpointsFor,
  htmlCatalogError,
  isApiStyle,
  isMediaNativeKind,
  isMediaOnlyKind,
  isProviderKind,
  normalizeBaseURL,
  officialSiblingEndpoints,
  parseProviderKind,
  pickApiStyle,
  presetFor,
  presetModel,
  PROVIDER_KINDS,
  PROVIDER_PRESETS,
  resolveCatalogBaseURL,
  supportedApiStylesFor,
  type ApiStyle,
  type CatalogAdvice,
  type CatalogErrorCode,
  type CatalogModel,
  type CatalogSource,
  type PresetGroup,
  type PresetRegion,
  type ProviderKind,
  type ProviderPreset
} from "./presets/index.ts"
