export { parseGitignore, shouldIgnore } from "./sources/ignore"
export { collectKnowledgeFiles } from "./sources/collect-files"
export { canParse, parseDocument, type ParseDocumentOptions } from "./parsers"
export { chunkText, chunkId, type TextChunk } from "./indexer/chunk"
export { embeddingsNeedRebuild } from "./indexer/stale"
export { cosineSimilarity, rankByCosine, lexicalScore } from "./retriever/cosine"
export { mapHitLineRange, pinHitToQuery, type HitLineRange } from "./retriever/hit-line-range"
export { blendRerankScore, rerankHits } from "./retriever/rerank"
export { rerankWithProvider, fallbackLocalRerank } from "./retriever/provider-rerank"
export { hashedEmbedding } from "./retriever/embed"
